import Head from 'next/head'
import { Open_Sans } from 'next/font/google'

import dynamic from 'next/dynamic'
const Calendar = dynamic(import('@/components/Calendar'))
import CalendarProvider from '@/components/CalendarProvider'
import { useEffect, useState } from 'react'

const OpenSans = Open_Sans({ subsets: ['latin'] })

export default function Home() {
  const [winReady, setwinReady] = useState(false)
  useEffect(() => {
    setwinReady(true)
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={OpenSans.className}>
        <CalendarProvider>{winReady ? <Calendar /> : null}</CalendarProvider>
      </main>
    </>
  )
}
